/** Declaration file generated by dts-gen */

export = unfluff;

declare function unfluff(html: any, language: any): any;

declare namespace unfluff {
    const prototype: {
    };

    function lazy(html: any, language: any): any;

    namespace lazy {
        const prototype: {
        };

    }

}

